### ISSUE TITLE
map with multiple venues

### ISSUE THREAD

**Issue by petschki** [collective/collective.venue#10]
I'm trying to use collective.venue to show multiple venues on a map. 
My idea was to create a collection with venues and select a template which places a viewlet above (or below ... configurable?) the contentbody with a map showing all marks of the venues. This would be even nicer in combination with `collective.collectionfilter` which would enable filtering the venue marks on the map ... 

This is quite similar to collective.geo.locationmap (which I used here long time ago: http://www.wohin-heute.at/freizeitbetriebe )  but this doesn't work in Plone 5 anymore and I don't want to mess around with the heavyweight collective.geo.* addons ...

@thet maybe you can give me a pointer, how to achive this in leafletjs with pat-leaflet?

**Comment by thet** [comment]
glad you asked!
this should help: http://patternslib.github.io/pat-leaflet/

**Comment by thet** [comment]
related: https://github.com/collective/collective.venue/pull/13

**Comment by petschki** [comment]
I'll close this as its merged in `collective.collectionfilter` master
