### ISSUE TITLE
Traceback if I call /@@venue-controlpanel

### ISSUE THREAD

**Issue by woolyseal** [collective/collective.venue#3]
I encountered a traceback after I installed Venue [geolocation] and tried to call /@@venue-controlpanel.

**Versions:**
Plone = 5.0.6rc1
Plone Patternslib = 1.0
collective.geolocationbehavior = 1.5.1
collective.venue base profile = 3.1.1

**Traceback:**
`
Es ist leider ein Fehler aufgetreten…

Dies ist die vollständige Fehlermeldung:

Zeige Fehlerbericht als Text

Traceback (innermost last):

    Module ZPublisher.Publish, line 138, in publish
    Module ZPublisher.mapply, line 77, in mapply
    Module ZPublisher.Publish, line 48, in call_object
    Module plone.z3cform.layout, line 66, in __call__
    Module plone.z3cform.layout, line 60, in update
    Module z3c.form.form, line 162, in render
    Module zope.browserpage.viewpagetemplatefile, line 51, in __call__
    Module zope.pagetemplate.pagetemplate, line 132, in pt_render
    Module five.pt.engine, line 98, in __call__
    Module z3c.pt.pagetemplate, line 163, in render
    Module chameleon.zpt.template, line 261, in render
    Module chameleon.template, line 171, in render
    Module 2e226ec8d5a364c7bb94a9af6df7cf43.py, line 91, in render
    Module 52f963cda721cddd1087a721b7303fc4.py, line 1806, in render_titlelessform
    Module 52f963cda721cddd1087a721b7303fc4.py, line 451, in render_fields
    Module 52f963cda721cddd1087a721b7303fc4.py, line 126, in render_widget_rendering
    Module 52f963cda721cddd1087a721b7303fc4.py, line 1069, in render_field
    Module five.pt.expressions, line 161, in __call__
    Module Products.Five.browser.metaconfigure, line 485, in __call__
    Module zope.browserpage.viewpagetemplatefile, line 83, in __call__
    Module zope.browserpage.viewpagetemplatefile, line 51, in __call__
    Module zope.pagetemplate.pagetemplate, line 132, in pt_render
    Module five.pt.engine, line 98, in __call__
    Module z3c.pt.pagetemplate, line 163, in render
    Module chameleon.zpt.template, line 261, in render
    Module chameleon.template, line 191, in render
    Module chameleon.template, line 171, in render
    Module b29bad6a2df27580e36641c2d93515e6.py, line 591, in render
    Module b29bad6a2df27580e36641c2d93515e6.py, line 466, in render_widget_wrapper
    Module five.pt.expressions, line 161, in __call__
    Module plone.app.z3cform.widget, line 90, in render
    Module plone.app.widgets.base, line 111, in render
    Module plone.app.widgets.base, line 102, in update
    Module json, line 244, in dumps
    Module json.encoder, line 207, in encode
    Module json.encoder, line 270, in iterencode
    Module json.encoder, line 184, in default

TypeError: <function get_site at 0x7f1b8113c050> is not JSON serializable

 - Expression: "widget/@@ploneform-render-widget"
 - Filename:   ... rm-1.2.1-py2.7.egg/plone/app/z3cform/templates/macros.pt
 - Location:   (line 98: col 81)
 - Source:     ... place="structure widget/@@ploneform-render-widget"/>
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Expression: "widget/render"
 - Filename:   ... rm-1.2.1-py2.7.egg/plone/app/z3cform/templates/widget.pt
 - Location:   (line 38: col 46)
 - Source:     ... xt" tal:replace="structure widget/render"
                                              ^^^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               context: <RelatedItemsWidget search_base at 0x7f1b7ad57210>
               views: <ViewMapper - at 0x7f1b7b27d810>
               modules: <TraversableModuleImporter - at 0x7f1b8da4e6d0>
               args: <tuple - at 0x7f1b98153050>
               nothing: <NoneType - at 0x7883f0>
               target_language: <NoneType - at 0x7883f0>
               default: <object - at 0x7f1b98129c20>
               request: <instance - at 0x7f1b812673f8>
               wrapped_repeat: {...} (0)
               loop: {...} (0)
               template: <ViewPageTemplateFile - at 0x7f1b7af41710>
               translate: <function translate at 0x7f1b7b46a398>
               options: {...} (0)
               view: <RenderWidget ploneform-render-widget at 0x7f1b7b27d390>
`

**Comment by thet** [comment]
Please try the latest Plone 5.1 release and look if the error comes again... Maybe there are some changes which cause these error. I'm using Plone 5.1 myself in production...
http://dist.plone.org/release/5.1-latest/

**Comment by thet** [comment]
Probably fixed, otherwise please reopen.
