### ISSUE TITLE
Bundle. Structure, Compilation

### ISSUE THREAD

**Issue by ksuess** [collective/collective.venue#4]
Hi
I'm preparing a bundle for an add-on. I took this add-on as an orientation how to do this. 
May I ask how you got the compiled files. Is a gruntfile used for this? What is the prefered way to generate the compiled files?
Thank you for any hint, Katja

**Comment by ksuess** [comment]
Found it! 
https://docs.plone.org/adapt-and-extend/theming/resourceregistry.html#bundles-compiling-bundles

**Comment by thet** [comment]
hi,
i have a pending pull request, which i probably should go and merge it into master.
give me a moment to do that...
it contains useful fixes and a already compiled bundle too.

**Comment by thet** [comment]
Done. Release is following soon.
If you want the geolocation feature with leaflet map integration, depend on this package with the  'geolocation' extra. E.g.

```
eggs =
    collective.venue [geolocation]
```
