### ISSUE TITLE
What about setting z3c.unconfigure <= 1.1 as a requirement?

### ISSUE THREAD

**Issue by arsenico13** [collective/collective.venue#6]
Hi @thet,
What do you think on changing the requirement of `collective.venue` from 
`z3c.unconfigure < 1.1`
to
`z3c.unconfigure <= 1.1` ?

I ask this because from the version 5.1 and greater of Plone (in http://dist.plone.org) there's `z3c.unconfigure` pinned to version 1.1.

See here:
http://dist.plone.org/release/5.1/versions.cfg
http://dist.plone.org/release/5.1.1/versions.cfg
http://dist.plone.org/release/5.1rc2/versions.cfg

Whith `<=` it could be used with both `buildout.coredev` and the release of Plone >= 5.1.

**Comment by thet** [comment]
thanks for pointing that out!
i pinned to z3c.unconfigure < 1.1 because it depends on zope.configuration >= 3.8.0.

I've created a PR, see: #7
