### ISSUE TITLE
Override of standard event accessor also when product is not installed

### ISSUE THREAD

**Issue by cekk** [collective/collective.venue#9]
I added this product in a buildout with several websites.
I need to install this product only on one website.

The problem is that in the other websites, standard events use collective.venue eventaccessor adapter instead the default one, because there is an unconfigure directive.
This cause some problems in some views (for example event_summary) where they try to access the location accessor, and it returns None also when the field is correctly set.

Is there a different way to override the accessor? Maybe only when the product is installed or better when the event has the behavior enabled? Maybe registering the accessor for behavior's interface?

**Comment by thet** [comment]
@cekk Registering the accessor for a behavior sounds like a good idea. The IEventAccessor is registered for IDXEvent, see: https://github.com/plone/plone.app.event/blob/master/plone/app/event/dx/behaviors.py#L399
If it could be registered for the ``collective.venue.behaviors.ILocation`` behavior instead, this could work.

I'm happy to accept a PR :)

**Comment by thet** [comment]
Fixed via #12
